variables:
  CI: true

trigger:
  paths:
    include:
    - "+msise00/*"
    - azure-pipelines.yml

pool:
  vmImage: ubuntu-latest
steps:
  - script: |
      sudo apt update -q
      sudo apt install -yq --no-install-recommends gfortran
    displayName: 'Install Linux prereqs'
  - task: InstallMATLAB@0
  - task: RunMATLABCommand@0
    inputs:
      command: "disp(version); TestAll"
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: test-results/results.xml
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: code-coverage/coverage.xml
