name: ci_mac

env:
  CMAKE_GENERATOR: Ninja

on:
  push:
    paths:
    - "**.py"
    - .github/workflows/ci_mac.yml
  pull_request:

jobs:

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - run: brew install ninja
    - run: pip install .[tests]

    - run: pytest
      env:
        CC: gcc-9
        FC: gfortran-9
