name: ci_mac

on:
  push:
    paths:
    - "**.py"
    - .github/workflows/ci_mac.yml

jobs:

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install .[tests]

    - run: pytest
      env:
        CC: gcc-9
        FC: gfortran-9
